cd vis

CUDA_VISIBLE_DEVICES=0 nohup python runvis.py densenet121_nofc_fd_none_nohead_dan_none_nohead  notrick_output  log/densenet121_nofc_fd_none_nohead_dan_none_nohead__crit_xent__sb___b___sl_0__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__0/checkpoint_ep60.pth.tar &

CUDA_VISIBLE_DEVICES=1 nohup python runvis.py densenet121_nofc_fd_none_nohead_dan_none_nohead  singular_output  log/densenet121_nofc_fd_none_nohead_dan_none_nohead__crit_singular__sb_1e-7__b___sl_-15__fcl_True__reg_none__dropout_none__dau_crop__pp_before__size_256__0/checkpoint_ep60.pth.tar &


CUDA_VISIBLE_DEVICES=2 nohup python runvis.py densenet121_newfd_nofc_fd_ab_nohead_dan_none_nohead  newfd_output  log/densenet121_newfd_nofc_fd_ab_nohead_dan_none_nohead__crit_xent__sb___b___sl_0__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__open_fd__0/checkpoint_ep60.pth.tar &


sleep 180m

CUDA_VISIBLE_DEVICES=3 nohup python runvis.py densenet121_nofc_fd_none_nohead_dan_none_nohead  newsing_output  layer5_log/densenet121_nofc_fd_none_nohead_dan_none_nohead__crit_xent__sb_1e-7__b___sl_-15__fcl_True__reg_none__dropout_none__dau_crop__pp_before__size_256__open_fd__0/checkpoint_ep60.pth.tar &



# 'log/densenet121_fc512_fd_none_nohead_dan_none_nohead__crit_xent__sb___b___sl_0__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__0/checkpoint_ep60.pth.tar'
