sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead --save-dir combine_log/densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-7__b_1e-3__sl_15__fcl_True__reg_svmo__dropout_none__dau_crop__pp_cam__size_256__0 --gpu-devices 0 --criterion singular --fix-custom-loss --switch-loss 10 --regularizer svmo --dropout none --data-augment crop --penalty-position cam &
sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead --save-dir combine_log/densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-7__b_1e-3__sl_15__fcl_True__reg_svmo__dropout_none__dau_crop__pp_cam__size_256__1 --gpu-devices 1 --criterion singular --fix-custom-loss --switch-loss 10 --regularizer svmo --dropout none --data-augment crop --penalty-position cam &
sing_beta=1e-7 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead --save-dir combine_log/densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-7__b___sl_15__fcl_True__reg_none__dropout_none__dau_crop__pp_cam__size_256__0 --gpu-devices 3 --criterion singular --fix-custom-loss --switch-loss 10 --regularizer none --dropout none --data-augment crop --penalty-position cam &
sing_beta=1e-7 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead --save-dir combine_log/densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-7__b___sl_15__fcl_True__reg_none__dropout_none__dau_crop__pp_cam__size_256__1 --gpu-devices 4 --criterion singular --fix-custom-loss --switch-loss 10 --regularizer none --dropout none --data-augment crop --penalty-position cam &
sing_beta= beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead --save-dir combine_log/densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead__crit_xent__sb___b_1e-3__sl_0__fcl_False__reg_svmo__dropout_none__dau_crop__pp_before__size_256__0 --gpu-devices 5 --criterion xent  --switch-loss 0 --regularizer svmo --dropout none --data-augment crop --penalty-position before &

sleep 270m

sing_beta= beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead --save-dir combine_log/densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead__crit_xent__sb___b_1e-3__sl_0__fcl_False__reg_svmo__dropout_none__dau_crop__pp_before__size_256__1 --gpu-devices 0 --criterion xent  --switch-loss 0 --regularizer svmo --dropout none --data-augment crop --penalty-position before &
sing_beta=1e-7 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a densenet121_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir combine_log/densenet121_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-7__b___sl_15__fcl_True__reg_none__dropout_none__dau_crop__pp_cam__size_256__0 --gpu-devices 1 --criterion singular --fix-custom-loss --switch-loss 10 --regularizer none --dropout none --data-augment crop --penalty-position cam &
sing_beta=1e-7 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a densenet121_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir combine_log/densenet121_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-7__b___sl_15__fcl_True__reg_none__dropout_none__dau_crop__pp_cam__size_256__1 --gpu-devices 3 --criterion singular --fix-custom-loss --switch-loss 10 --regularizer none --dropout none --data-augment crop --penalty-position cam &
sing_beta= beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a densenet121_fc512_fd_none_nohead_dan_none_nohead --save-dir combine_log/densenet121_fc512_fd_none_nohead_dan_none_nohead__crit_htri__sb___b___sl_0__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__1 --gpu-devices 4 --criterion htri  --switch-loss 0 --regularizer none --dropout none --data-augment crop --penalty-position before &
sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a densenet121_nofc_fd_ab_nohead_dan_cam_pam_nohead --save-dir combine_log/densenet121_nofc_fd_ab_nohead_dan_cam_pam_nohead__crit_singular_htri__sb_1e-7__b_1e-3__sl_15__fcl_True__reg_svmo__dropout_none__dau_crop__pp_cam__size_256__1 --gpu-devices 5 --criterion singular_htri --fix-custom-loss --switch-loss 10 --regularizer svmo --dropout none --data-augment crop --penalty-position cam &

