sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead --save-dir combine_log/densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead__crit_singular_htri__sb_1e-7__b_1e-3__sl_12__fcl_True__reg_svmo__dropout_incr__dau_crop__pp_cam__size_256__0 --gpu-devices 0 --criterion singular_htri --fix-custom-loss --switch-loss 12 --regularizer svmo --dropout incr --data-augment crop --penalty-position cam &
sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead --save-dir combine_log/densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead__crit_singular_htri__sb_1e-7__b_1e-3__sl_12__fcl_True__reg_svmo__dropout_incr__dau_crop__pp_cam__size_256__1 --gpu-devices 1 --criterion singular_htri --fix-custom-loss --switch-loss 12 --regularizer svmo --dropout incr --data-augment crop --penalty-position cam &
sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 384 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead --save-dir combine_log/densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead__crit_singular_htri__sb_1e-7__b_1e-3__sl_12__fcl_True__reg_svmo__dropout_none__dau_crop__pp_cam__size_384__0 --gpu-devices 3 --criterion singular_htri --fix-custom-loss --switch-loss 12 --regularizer svmo --dropout none --data-augment crop --penalty-position cam &
sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 384 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead --save-dir combine_log/densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead__crit_singular_htri__sb_1e-7__b_1e-3__sl_12__fcl_True__reg_svmo__dropout_none__dau_crop__pp_cam__size_384__1 --gpu-devices 4 --criterion singular_htri --fix-custom-loss --switch-loss 12 --regularizer svmo --dropout none --data-augment crop --penalty-position cam &
sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 384 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead --save-dir combine_log/densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead__crit_singular_htri__sb_1e-7__b_1e-3__sl_12__fcl_True__reg_svmo__dropout_incr__dau_crop__pp_cam__size_384__0 --gpu-devices 5 --criterion singular_htri --fix-custom-loss --switch-loss 12 --regularizer svmo --dropout incr --data-augment crop --penalty-position cam &

sleep 330m

sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 384 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead --save-dir combine_log/densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead__crit_singular_htri__sb_1e-7__b_1e-3__sl_12__fcl_True__reg_svmo__dropout_incr__dau_crop__pp_cam__size_384__1 --gpu-devices 0 --criterion singular_htri --fix-custom-loss --switch-loss 12 --regularizer svmo --dropout incr --data-augment crop --penalty-position cam &
sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 384 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead --save-dir combine_log/densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead__crit_singular_htri__sb_1e-7__b_1e-3__sl_12__fcl_True__reg_svmo__dropout_none__dau_color-jitter__pp_cam__size_384__0 --gpu-devices 1 --criterion singular_htri --fix-custom-loss --switch-loss 12 --regularizer svmo --dropout none --data-augment color-jitter --penalty-position cam &
sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 384 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead --save-dir combine_log/densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead__crit_singular_htri__sb_1e-7__b_1e-3__sl_12__fcl_True__reg_svmo__dropout_none__dau_color-jitter__pp_cam__size_384__1 --gpu-devices 3 --criterion singular_htri --fix-custom-loss --switch-loss 12 --regularizer svmo --dropout none --data-augment color-jitter --penalty-position cam &
sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 384 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead --save-dir combine_log/densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead__crit_singular_htri__sb_1e-7__b_1e-3__sl_12__fcl_True__reg_svmo__dropout_none__dau_crop,color-jitter__pp_cam__size_384__0 --gpu-devices 4 --criterion singular_htri --fix-custom-loss --switch-loss 12 --regularizer svmo --dropout none --data-augment crop,color-jitter --penalty-position cam &
sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 384 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead --save-dir combine_log/densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead__crit_singular_htri__sb_1e-7__b_1e-3__sl_12__fcl_True__reg_svmo__dropout_none__dau_crop,color-jitter__pp_cam__size_384__1 --gpu-devices 5 --criterion singular_htri --fix-custom-loss --switch-loss 12 --regularizer svmo --dropout none --data-augment crop,color-jitter --penalty-position cam &

sleep 330m

sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 384 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead --save-dir combine_log/densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead__crit_singular_htri__sb_1e-7__b_1e-3__sl_12__fcl_True__reg_svmo__dropout_none__dau_crop,random-erase__pp_cam__size_384__0 --gpu-devices 0 --criterion singular_htri --fix-custom-loss --switch-loss 12 --regularizer svmo --dropout none --data-augment crop,random-erase --penalty-position cam &
sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 384 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead --save-dir combine_log/densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead__crit_singular_htri__sb_1e-7__b_1e-3__sl_12__fcl_True__reg_svmo__dropout_none__dau_crop,random-erase__pp_cam__size_384__1 --gpu-devices 1 --criterion singular_htri --fix-custom-loss --switch-loss 12 --regularizer svmo --dropout none --data-augment crop,random-erase --penalty-position cam &
sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 384 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead --save-dir combine_log/densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead__crit_singular_htri__sb_1e-7__b_1e-3__sl_12__fcl_True__reg_svmo__dropout_none__dau_none__pp_cam__size_384__0 --gpu-devices 3 --criterion singular_htri --fix-custom-loss --switch-loss 12 --regularizer svmo --dropout none --data-augment none --penalty-position cam &
sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 384 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead --save-dir combine_log/densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead__crit_singular_htri__sb_1e-7__b_1e-3__sl_12__fcl_True__reg_svmo__dropout_none__dau_none__pp_cam__size_384__1 --gpu-devices 4 --criterion singular_htri --fix-custom-loss --switch-loss 12 --regularizer svmo --dropout none --data-augment none --penalty-position cam &
sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 384 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead --save-dir combine_log/densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead__crit_singular_htri__sb_1e-7__b_1e-3__sl_12__fcl_True__reg_svmo__dropout_incr__dau_crop,random-erase__pp_cam__size_384__0 --gpu-devices 5 --criterion singular_htri --fix-custom-loss --switch-loss 12 --regularizer svmo --dropout incr --data-augment crop,random-erase --penalty-position cam &

sleep 330m

sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 384 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead --save-dir combine_log/densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead__crit_singular_htri__sb_1e-7__b_1e-3__sl_12__fcl_True__reg_svmo__dropout_incr__dau_crop,random-erase__pp_cam__size_384__1 --gpu-devices 0 --criterion singular_htri --fix-custom-loss --switch-loss 12 --regularizer svmo --dropout incr --data-augment crop,random-erase --penalty-position cam &
sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 384 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead --save-dir combine_log/densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead__crit_singular_htri__sb_1e-7__b_1e-3__sl_12__fcl_True__reg_svmo__dropout_incr__dau_random-erase__pp_cam__size_384__0 --gpu-devices 1 --criterion singular_htri --fix-custom-loss --switch-loss 12 --regularizer svmo --dropout incr --data-augment random-erase --penalty-position cam &
sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 384 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead --save-dir combine_log/densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead__crit_singular_htri__sb_1e-7__b_1e-3__sl_12__fcl_True__reg_svmo__dropout_incr__dau_random-erase__pp_cam__size_384__1 --gpu-devices 3 --criterion singular_htri --fix-custom-loss --switch-loss 12 --regularizer svmo --dropout incr --data-augment random-erase --penalty-position cam &
sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 384 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead --save-dir combine_log/densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead__crit_singular_htri__sb_1e-7__b_1e-3__sl_12__fcl_True__reg_svmo__dropout_incr__dau_crop,color-jitter__pp_cam__size_384__0 --gpu-devices 4 --criterion singular_htri --fix-custom-loss --switch-loss 12 --regularizer svmo --dropout incr --data-augment crop,color-jitter --penalty-position cam &
sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 384 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead --save-dir combine_log/densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead__crit_singular_htri__sb_1e-7__b_1e-3__sl_12__fcl_True__reg_svmo__dropout_incr__dau_crop,color-jitter__pp_cam__size_384__1 --gpu-devices 5 --criterion singular_htri --fix-custom-loss --switch-loss 12 --regularizer svmo --dropout incr --data-augment crop,color-jitter --penalty-position cam &

sleep 330m

sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 384 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead --save-dir combine_log/densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead__crit_singular_htri__sb_1e-7__b_1e-3__sl_12__fcl_True__reg_svmo__dropout_incr__dau_color-jitter__pp_cam__size_384__0 --gpu-devices 0 --criterion singular_htri --fix-custom-loss --switch-loss 12 --regularizer svmo --dropout incr --data-augment color-jitter --penalty-position cam &
sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 384 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead --save-dir combine_log/densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead__crit_singular_htri__sb_1e-7__b_1e-3__sl_12__fcl_True__reg_svmo__dropout_incr__dau_color-jitter__pp_cam__size_384__1 --gpu-devices 1 --criterion singular_htri --fix-custom-loss --switch-loss 12 --regularizer svmo --dropout incr --data-augment color-jitter --penalty-position cam &
sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 384 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead --save-dir combine_log/densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead__crit_singular_htri__sb_1e-7__b_1e-3__sl_12__fcl_True__reg_svmo__dropout_incr__dau_none__pp_cam__size_384__0 --gpu-devices 3 --criterion singular_htri --fix-custom-loss --switch-loss 12 --regularizer svmo --dropout incr --data-augment none --penalty-position cam &
sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 384 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead --save-dir combine_log/densenet121_fc512_fd_ab_nohead_dan_cam_pam_nohead__crit_singular_htri__sb_1e-7__b_1e-3__sl_12__fcl_True__reg_svmo__dropout_incr__dau_none__pp_cam__size_384__1 --gpu-devices 4 --criterion singular_htri --fix-custom-loss --switch-loss 12 --regularizer svmo --dropout incr --data-augment none --penalty-position cam &


