sing_beta=1e-6 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 80 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-6__b___sl_-25__fcl_True__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_80__0 --gpu-devices 0 --criterion singular --fix-custom-loss --switch-loss -25 --regularizer none --dropout none --data-augment crop --penalty-position before &
sing_beta=1e-6 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 80 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-6__b___sl_-25__fcl_True__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_80__1 --gpu-devices 1 --criterion singular --fix-custom-loss --switch-loss -25 --regularizer none --dropout none --data-augment crop --penalty-position before &
sing_beta=5e-7 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 80 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_5e-7__b___sl_-25__fcl_True__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_80__0 --gpu-devices 3 --criterion singular --fix-custom-loss --switch-loss -25 --regularizer none --dropout none --data-augment crop --penalty-position before &
sing_beta=5e-7 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 80 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_5e-7__b___sl_-25__fcl_True__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_80__1 --gpu-devices 4 --criterion singular --fix-custom-loss --switch-loss -25 --regularizer none --dropout none --data-augment crop --penalty-position before &
sing_beta=1e-7 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 80 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-7__b___sl_-25__fcl_True__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_80__0 --gpu-devices 5 --criterion singular --fix-custom-loss --switch-loss -25 --regularizer none --dropout none --data-augment crop --penalty-position before &
sing_beta=1e-7 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 80 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-7__b___sl_-25__fcl_True__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_80__1 --gpu-devices 6 --criterion singular --fix-custom-loss --switch-loss -25 --regularizer none --dropout none --data-augment crop --penalty-position before &
sing_beta=5e-8 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 80 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_5e-8__b___sl_-25__fcl_True__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_80__0 --gpu-devices 7 --criterion singular --fix-custom-loss --switch-loss -25 --regularizer none --dropout none --data-augment crop --penalty-position before &

sleep 170m

sing_beta=5e-8 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 80 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_5e-8__b___sl_-25__fcl_True__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_80__1 --gpu-devices 0 --criterion singular --fix-custom-loss --switch-loss -25 --regularizer none --dropout none --data-augment crop --penalty-position before &
sing_beta=1e-8 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 80 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-8__b___sl_-25__fcl_True__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_80__0 --gpu-devices 1 --criterion singular --fix-custom-loss --switch-loss -25 --regularizer none --dropout none --data-augment crop --penalty-position before &
sing_beta=1e-8 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 80 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-8__b___sl_-25__fcl_True__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_80__1 --gpu-devices 3 --criterion singular --fix-custom-loss --switch-loss -25 --regularizer none --dropout none --data-augment crop --penalty-position before &
sing_beta=1e-8 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 80 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-8__b___sl_-25__fcl_True__reg_none__dropout_none__dau_crop__pp_after__size_256__ep_80__0 --gpu-devices 4 --criterion singular --fix-custom-loss --switch-loss -25 --regularizer none --dropout none --data-augment crop --penalty-position after &
sing_beta=1e-8 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 80 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-8__b___sl_-25__fcl_True__reg_none__dropout_none__dau_crop__pp_after__size_256__ep_80__1 --gpu-devices 5 --criterion singular --fix-custom-loss --switch-loss -25 --regularizer none --dropout none --data-augment crop --penalty-position after &
sing_beta=5e-8 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 80 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_5e-8__b___sl_-25__fcl_True__reg_none__dropout_none__dau_crop__pp_after__size_256__ep_80__0 --gpu-devices 6 --criterion singular --fix-custom-loss --switch-loss -25 --regularizer none --dropout none --data-augment crop --penalty-position after &
sing_beta=5e-8 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 80 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_5e-8__b___sl_-25__fcl_True__reg_none__dropout_none__dau_crop__pp_after__size_256__ep_80__1 --gpu-devices 7 --criterion singular --fix-custom-loss --switch-loss -25 --regularizer none --dropout none --data-augment crop --penalty-position after &

sleep 170m

sing_beta=1e-7 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 80 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-7__b___sl_-25__fcl_True__reg_none__dropout_none__dau_crop__pp_after__size_256__ep_80__0 --gpu-devices 0 --criterion singular --fix-custom-loss --switch-loss -25 --regularizer none --dropout none --data-augment crop --penalty-position after &
sing_beta=1e-7 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 80 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-7__b___sl_-25__fcl_True__reg_none__dropout_none__dau_crop__pp_after__size_256__ep_80__1 --gpu-devices 1 --criterion singular --fix-custom-loss --switch-loss -25 --regularizer none --dropout none --data-augment crop --penalty-position after &
sing_beta=5e-7 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 80 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_5e-7__b___sl_-25__fcl_True__reg_none__dropout_none__dau_crop__pp_after__size_256__ep_80__0 --gpu-devices 3 --criterion singular --fix-custom-loss --switch-loss -25 --regularizer none --dropout none --data-augment crop --penalty-position after &
sing_beta=5e-7 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 80 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_5e-7__b___sl_-25__fcl_True__reg_none__dropout_none__dau_crop__pp_after__size_256__ep_80__1 --gpu-devices 4 --criterion singular --fix-custom-loss --switch-loss -25 --regularizer none --dropout none --data-augment crop --penalty-position after &
sing_beta=1e-6 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 80 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-6__b___sl_-25__fcl_True__reg_none__dropout_none__dau_crop__pp_after__size_256__ep_80__0 --gpu-devices 5 --criterion singular --fix-custom-loss --switch-loss -25 --regularizer none --dropout none --data-augment crop --penalty-position after &
sing_beta=1e-6 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 80 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-6__b___sl_-25__fcl_True__reg_none__dropout_none__dau_crop__pp_after__size_256__ep_80__1 --gpu-devices 6 --criterion singular --fix-custom-loss --switch-loss -25 --regularizer none --dropout none --data-augment crop --penalty-position after &

sleep 170m

sing_beta=1e-6 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-6__b___sl_-15__fcl_True__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__0 --gpu-devices 0 --criterion singular --fix-custom-loss --switch-loss -15 --regularizer none --dropout none --data-augment crop --penalty-position before &
sing_beta=1e-6 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-6__b___sl_-15__fcl_True__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__1 --gpu-devices 1 --criterion singular --fix-custom-loss --switch-loss -15 --regularizer none --dropout none --data-augment crop --penalty-position before &
sing_beta=5e-7 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_5e-7__b___sl_-15__fcl_True__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__0 --gpu-devices 3 --criterion singular --fix-custom-loss --switch-loss -15 --regularizer none --dropout none --data-augment crop --penalty-position before &
sing_beta=5e-7 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_5e-7__b___sl_-15__fcl_True__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__1 --gpu-devices 4 --criterion singular --fix-custom-loss --switch-loss -15 --regularizer none --dropout none --data-augment crop --penalty-position before &
sing_beta=1e-7 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-7__b___sl_-15__fcl_True__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__0 --gpu-devices 5 --criterion singular --fix-custom-loss --switch-loss -15 --regularizer none --dropout none --data-augment crop --penalty-position before &
sing_beta=1e-7 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-7__b___sl_-15__fcl_True__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__1 --gpu-devices 6 --criterion singular --fix-custom-loss --switch-loss -15 --regularizer none --dropout none --data-augment crop --penalty-position before &
sing_beta=5e-8 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_5e-8__b___sl_-15__fcl_True__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__0 --gpu-devices 7 --criterion singular --fix-custom-loss --switch-loss -15 --regularizer none --dropout none --data-augment crop --penalty-position before &

sleep 150m

sing_beta=5e-8 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_5e-8__b___sl_-15__fcl_True__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__1 --gpu-devices 0 --criterion singular --fix-custom-loss --switch-loss -15 --regularizer none --dropout none --data-augment crop --penalty-position before &
sing_beta=1e-8 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-8__b___sl_-15__fcl_True__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__0 --gpu-devices 1 --criterion singular --fix-custom-loss --switch-loss -15 --regularizer none --dropout none --data-augment crop --penalty-position before &
sing_beta=1e-8 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-8__b___sl_-15__fcl_True__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__1 --gpu-devices 3 --criterion singular --fix-custom-loss --switch-loss -15 --regularizer none --dropout none --data-augment crop --penalty-position before &
sing_beta=1e-8 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-8__b___sl_-15__fcl_True__reg_none__dropout_none__dau_crop__pp_after__size_256__ep_60__0 --gpu-devices 4 --criterion singular --fix-custom-loss --switch-loss -15 --regularizer none --dropout none --data-augment crop --penalty-position after &
sing_beta=1e-8 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-8__b___sl_-15__fcl_True__reg_none__dropout_none__dau_crop__pp_after__size_256__ep_60__1 --gpu-devices 5 --criterion singular --fix-custom-loss --switch-loss -15 --regularizer none --dropout none --data-augment crop --penalty-position after &
sing_beta=5e-8 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_5e-8__b___sl_-15__fcl_True__reg_none__dropout_none__dau_crop__pp_after__size_256__ep_60__0 --gpu-devices 6 --criterion singular --fix-custom-loss --switch-loss -15 --regularizer none --dropout none --data-augment crop --penalty-position after &
sing_beta=5e-8 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_5e-8__b___sl_-15__fcl_True__reg_none__dropout_none__dau_crop__pp_after__size_256__ep_60__1 --gpu-devices 7 --criterion singular --fix-custom-loss --switch-loss -15 --regularizer none --dropout none --data-augment crop --penalty-position after &

sleep 150m

sing_beta=1e-7 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-7__b___sl_-15__fcl_True__reg_none__dropout_none__dau_crop__pp_after__size_256__ep_60__0 --gpu-devices 0 --criterion singular --fix-custom-loss --switch-loss -15 --regularizer none --dropout none --data-augment crop --penalty-position after &
sing_beta=1e-7 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-7__b___sl_-15__fcl_True__reg_none__dropout_none__dau_crop__pp_after__size_256__ep_60__1 --gpu-devices 1 --criterion singular --fix-custom-loss --switch-loss -15 --regularizer none --dropout none --data-augment crop --penalty-position after &
sing_beta=5e-7 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_5e-7__b___sl_-15__fcl_True__reg_none__dropout_none__dau_crop__pp_after__size_256__ep_60__0 --gpu-devices 3 --criterion singular --fix-custom-loss --switch-loss -15 --regularizer none --dropout none --data-augment crop --penalty-position after &
sing_beta=5e-7 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_5e-7__b___sl_-15__fcl_True__reg_none__dropout_none__dau_crop__pp_after__size_256__ep_60__1 --gpu-devices 4 --criterion singular --fix-custom-loss --switch-loss -15 --regularizer none --dropout none --data-augment crop --penalty-position after &
sing_beta=1e-6 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-6__b___sl_-15__fcl_True__reg_none__dropout_none__dau_crop__pp_after__size_256__ep_60__0 --gpu-devices 5 --criterion singular --fix-custom-loss --switch-loss -15 --regularizer none --dropout none --data-augment crop --penalty-position after &
sing_beta=1e-6 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir new_resnet_log/resnet50_sf_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-6__b___sl_-15__fcl_True__reg_none__dropout_none__dau_crop__pp_after__size_256__ep_60__1 --gpu-devices 6 --criterion singular --fix-custom-loss --switch-loss -15 --regularizer none --dropout none --data-augment crop --penalty-position after &
