sleep 60m

sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 384 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 70 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_sl1_nofc_fd_ab_nohead_dan_cam_pam_nohead --save-dir sl1_resnet_log/resnet50_sf_sl1_nofc_fd_ab_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-7__b_1e-3__sl_-45__fcl_False__reg_svmo__dropout_incr__dau_crop,random-erase__pp_before,after,cam,pam__size_384__ep_70__ucg_False__cg_0.5__0 --gpu-devices 0 --criterion singular  --switch-loss -45 --regularizer svmo --dropout incr --data-augment crop,random-erase --penalty-position before,after,cam,pam  --clip-grad 0.5 &

sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 384 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 70 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_sl1_fc512_fd_ab_nohead_dan_cam_pam_nohead --save-dir sl1_resnet_log/resnet50_sf_sl1_fc512_fd_ab_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-7__b_1e-3__sl_-45__fcl_False__reg_svmo__dropout_incr__dau_crop,random-erase__pp_before,after,cam,pam__size_384__ep_70__ucg_False__cg_0.5__0 --gpu-devices 1 --criterion singular  --switch-loss -45 --regularizer svmo --dropout incr --data-augment crop,random-erase --penalty-position before,after,cam,pam  --clip-grad 0.5 &

sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 384 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 70 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_sl1_fc1024_fd_ab_nohead_dan_cam_pam_nohead --save-dir sl1_resnet_log/resnet50_sf_sl1_fc1024_fd_ab_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-7__b_1e-3__sl_-45__fcl_False__reg_svmo__dropout_incr__dau_crop,random-erase__pp_before,after,cam,pam__size_384__ep_70__ucg_False__cg_0.5__0 --gpu-devices 3 --criterion singular  --switch-loss -45 --regularizer svmo --dropout incr --data-augment crop,random-erase --penalty-position before,after,cam,pam  --clip-grad 0.5 &


sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 384 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 70 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_sl1_nofc_fd_ab_nohead_dan_cam_pam_nohead --save-dir sl1_resnet_log/resnet50_sf_sl1_nofc_fd_ab_nohead_dan_cam_pam_nohead__crit_singular_htri__sb_1e-7__b_1e-3__sl_-35__fcl_False__reg_svmo__dropout_incr__dau_crop,random-erase__pp_before,after,cam,pam__size_384__ep_70__ucg_False__cg_0.5__0 --gpu-devices 4 --criterion singular_htri  --switch-loss -35 --regularizer svmo --dropout incr --data-augment crop,random-erase --penalty-position before,after,cam,pam  --clip-grad 0.5 &

sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 384 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 70 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_sl1_fc512_fd_ab_nohead_dan_cam_pam_nohead --save-dir sl1_resnet_log/resnet50_sf_sl1_fc512_fd_ab_nohead_dan_cam_pam_nohead__crit_singular_htri__sb_1e-7__b_1e-3__sl_-35__fcl_False__reg_svmo__dropout_incr__dau_crop,random-erase__pp_before,after,cam,pam__size_384__ep_70__ucg_False__cg_0.5__0 --gpu-devices 5 --criterion singular_htri  --switch-loss -35 --regularizer svmo --dropout incr --data-augment crop,random-erase --penalty-position before,after,cam,pam  --clip-grad 0.5 &

sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 384 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 70 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_sl1_fc1024_fd_ab_nohead_dan_cam_pam_nohead --save-dir sl1_resnet_log/resnet50_sf_sl1_fc1024_fd_ab_nohead_dan_cam_pam_nohead__crit_singular_htri__sb_1e-7__b_1e-3__sl_-35__fcl_False__reg_svmo__dropout_incr__dau_crop,random-erase__pp_before,after,cam,pam__size_384__ep_70__ucg_False__cg_0.5__0 --gpu-devices 6 --criterion singular_htri  --switch-loss -35 --regularizer svmo --dropout incr --data-augment crop,random-erase --penalty-position before,after,cam,pam  --clip-grad 0.5 &

