sing_beta= beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_ls1_nofc_fd_none_nohead_dan_none_nohead --save-dir 0206_trick_log/ls/resnet50_sf_ls1_nofc_fd_none_nohead_dan_none_nohead__crit_xent__sb___b___sl_0__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__0 --gpu-devices 0 --criterion xent  --switch-loss 0 --regularizer none --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 &

sing_beta=1e-7 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_ls1_nofc_fd_none_nohead_dan_cam_pam_nohead --save-dir 0206_trick_log/ls/resnet50_sf_ls1_nofc_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-7__b___sl_-35__fcl_False__reg_none__dropout_none__dau_crop__pp_after__size_256__ep_60__ucg_False__cg_0.5__0 --gpu-devices 1 --criterion singular  --switch-loss -35 --regularizer none --dropout none --data-augment crop --penalty-position after  --clip-grad 0.5 &

sing_beta= beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_ls1_fc1024_fd_none_nohead_dan_none_nohead --save-dir 0206_trick_log/ls/resnet50_sf_ls1_fc1024_fd_none_nohead_dan_none_nohead__crit_xent__sb___b___sl_0__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__0 --gpu-devices 3 --criterion xent  --switch-loss 0 --regularizer none --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 &

sing_beta=1e-7 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_ls1_fc1024_fd_none_nohead_dan_cam_pam_nohead --save-dir 0206_trick_log/ls/resnet50_sf_ls1_fc1024_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-7__b___sl_-35__fcl_False__reg_none__dropout_none__dau_crop__pp_after__size_256__ep_60__ucg_False__cg_0.5__0 --gpu-devices 4 --criterion singular  --switch-loss -35 --regularizer none --dropout none --data-augment crop --penalty-position after  --clip-grad 0.5 &

sing_beta= beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc1024_fd_none_nohead_dan_none_nohead --save-dir 0206_trick_log/ls/resnet50_sf_fc1024_fd_none_nohead_dan_none_nohead__crit_xent__sb___b___sl_0__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__0 --gpu-devices 5 --criterion xent  --switch-loss 0 --regularizer none --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 &
sing_beta=1e-7 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_fc1024_fd_none_nohead_dan_cam_pam_nohead --save-dir 0206_trick_log/ls/resnet50_sf_fc1024_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-7__b___sl_-35__fcl_False__reg_none__dropout_none__dau_crop__pp_after__size_256__ep_60__ucg_False__cg_0.5__0 --gpu-devices 6 --criterion singular  --switch-loss -35 --regularizer none --dropout none --data-augment crop --penalty-position after  --clip-grad 0.5 &

sing_beta=1e-7 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier classifier2 fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_tr1_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir 0206_trick_log/tr1/resnet50_sf_tr1_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-7__b___sl_-35__fcl_False__reg_none__dropout_none__dau_crop__pp_after__size_256__ep_60__ucg_False__cg_0.5__0 --gpu-devices 7 --criterion singular  --switch-loss -35 --regularizer none --dropout none --data-augment crop --penalty-position after  --clip-grad 0.5 &

sleep 210m


sing_beta=1e-7 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier classifier2 fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_tr1_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir 0206_trick_log/tr1/resnet50_sf_tr1_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-7__b___sl_-35__fcl_False__reg_none__dropout_none__dau_crop__pp_before,after,cam,pam__size_256__ep_60__ucg_False__cg_0.5__0 --gpu-devices 0 --criterion singular  --switch-loss -35 --regularizer none --dropout none --data-augment crop --penalty-position before,after,cam,pam  --clip-grad 0.5 &
sing_beta= beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier classifier2 fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_tr1_fc512_fd_none_nohead_dan_cam_pam_nohead --save-dir 0206_trick_log/tr1/resnet50_sf_tr1_fc512_fd_none_nohead_dan_cam_pam_nohead__crit_xent__sb___b___sl_0__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__0 --gpu-devices 1 --criterion xent  --switch-loss 0 --regularizer none --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 &
sing_beta= beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier classifier2 fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_tr1_fc512_fd_none_nohead_dan_none_nohead --save-dir 0206_trick_log/tr1/resnet50_sf_tr1_fc512_fd_none_nohead_dan_none_nohead__crit_xent__sb___b___sl_0__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__0 --gpu-devices 3 --criterion xent  --switch-loss 0 --regularizer none --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 &

sing_beta=1e-7 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier classifier2 fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_tr1_fc1024_fd_none_nohead_dan_cam_pam_nohead --save-dir 0206_trick_log/tr1/resnet50_sf_tr1_fc1024_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-7__b___sl_-35__fcl_False__reg_none__dropout_none__dau_crop__pp_after__size_256__ep_60__ucg_False__cg_0.5__0 --gpu-devices 4 --criterion singular  --switch-loss -35 --regularizer none --dropout none --data-augment crop --penalty-position after  --clip-grad 0.5 &

sing_beta=1e-7 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier classifier2 fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_tr1_fc1024_fd_none_nohead_dan_cam_pam_nohead --save-dir 0206_trick_log/tr1/resnet50_sf_tr1_fc1024_fd_none_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-7__b___sl_-35__fcl_False__reg_none__dropout_none__dau_crop__pp_before,after,cam,pam__size_256__ep_60__ucg_False__cg_0.5__0 --gpu-devices 5 --criterion singular  --switch-loss -35 --regularizer none --dropout none --data-augment crop --penalty-position before,after,cam,pam  --clip-grad 0.5 &
sing_beta= beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier classifier2 fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_tr1_fc1024_fd_none_nohead_dan_cam_pam_nohead --save-dir 0206_trick_log/tr1/resnet50_sf_tr1_fc1024_fd_none_nohead_dan_cam_pam_nohead__crit_xent__sb___b___sl_0__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__0 --gpu-devices 6 --criterion xent  --switch-loss 0 --regularizer none --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 &
sing_beta= beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier classifier2 fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_tr1_fc1024_fd_none_nohead_dan_none_nohead --save-dir 0206_trick_log/tr1/resnet50_sf_tr1_fc1024_fd_none_nohead_dan_none_nohead__crit_xent__sb___b___sl_0__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__0 --gpu-devices 7 --criterion xent  --switch-loss 0 --regularizer none --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 &
