sing_beta= beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_nofc_fd_ab_c_nohead_dan_cam_pam_nohead --save-dir supplement_resnet_log/resnet50_sf_nofc_fd_ab_c_nohead_dan_cam_pam_nohead__crit_xent__sb___b___sl_0__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__0 --gpu-devices 1 --criterion xent  --switch-loss 0 --regularizer none --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 &

sing_beta= beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_nofc_fd_ab_c_nohead_dan_cam_pam_nohead --save-dir supplement_resnet_log/resnet50_sf_nofc_fd_ab_c_nohead_dan_cam_pam_nohead__crit_xent__sb___b___sl_0__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__1 --gpu-devices 3 --criterion xent  --switch-loss 0 --regularizer none --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 &

sing_beta= beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_nofc_fd_ab_nohead_dan_cam_pam_nohead --save-dir supplement_resnet_log/resnet50_sf_nofc_fd_ab_nohead_dan_cam_pam_nohead__crit_xent__sb___b___sl_0__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__0 --gpu-devices 4 --criterion xent  --switch-loss 0 --regularizer none --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 &

sing_beta= beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_nofc_fd_ab_nohead_dan_cam_pam_nohead --save-dir supplement_resnet_log/resnet50_sf_nofc_fd_ab_nohead_dan_cam_pam_nohead__crit_xent__sb___b___sl_0__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__1 --gpu-devices 5 --criterion xent  --switch-loss 0 --regularizer none --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 &

sing_beta= beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_nofc_fd_a_nohead_dan_cam_pam_nohead --save-dir supplement_resnet_log/resnet50_sf_nofc_fd_a_nohead_dan_cam_pam_nohead__crit_xent__sb___b___sl_0__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__0 --gpu-devices 6 --criterion xent  --switch-loss 0 --regularizer none --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 &

sleep 120m

sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_nofc_fd_none_nohead_dan_none_nohead --save-dir supplement_resnet_log/resnet50_sf_nofc_fd_none_nohead_dan_none_nohead__crit_singular__sb_1e-7__b_1e-3__sl_-15__fcl_False__reg_svmo__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__0 --gpu-devices 1 --criterion singular  --switch-loss -15 --regularizer svmo --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 &
sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_nofc_fd_none_nohead_dan_none_nohead --save-dir supplement_resnet_log/resnet50_sf_nofc_fd_none_nohead_dan_none_nohead__crit_singular__sb_1e-7__b_1e-3__sl_-15__fcl_False__reg_svmo__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__1 --gpu-devices 3 --criterion singular  --switch-loss -15 --regularizer svmo --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 &
sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_nofc_fd_ab_nohead_dan_none_nohead --save-dir supplement_resnet_log/resnet50_sf_nofc_fd_ab_nohead_dan_none_nohead__crit_singular__sb_1e-7__b_1e-3__sl_-15__fcl_False__reg_svmo__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__0 --gpu-devices 4 --criterion singular  --switch-loss -15 --regularizer svmo --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 &
sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_nofc_fd_ab_nohead_dan_none_nohead --save-dir supplement_resnet_log/resnet50_sf_nofc_fd_ab_nohead_dan_none_nohead__crit_singular__sb_1e-7__b_1e-3__sl_-15__fcl_False__reg_svmo__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__1 --gpu-devices 5 --criterion singular  --switch-loss -15 --regularizer svmo --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 &

sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_nofc_fd_ab_c_nohead_dan_none_nohead --save-dir supplement_resnet_log/resnet50_sf_nofc_fd_ab_c_nohead_dan_none_nohead__crit_singular__sb_1e-7__b_1e-3__sl_-15__fcl_False__reg_svmo__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__0 --gpu-devices 6 --criterion singular  --switch-loss -15 --regularizer svmo --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 &

sleep 140m

sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_nofc_fd_ab_c_nohead_dan_none_nohead --save-dir supplement_resnet_log/resnet50_sf_nofc_fd_ab_c_nohead_dan_none_nohead__crit_singular__sb_1e-7__b_1e-3__sl_-15__fcl_False__reg_svmo__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__1 --gpu-devices 0 --criterion singular  --switch-loss -15 --regularizer svmo --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 &

sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_nofc_fd_a_nohead_dan_none_nohead --save-dir supplement_resnet_log/resnet50_sf_nofc_fd_a_nohead_dan_none_nohead__crit_singular__sb_1e-7__b_1e-3__sl_-15__fcl_False__reg_svmo__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__0 --gpu-devices 1 --criterion singular  --switch-loss -15 --regularizer svmo --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 &
sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_nofc_fd_a_nohead_dan_none_nohead --save-dir supplement_resnet_log/resnet50_sf_nofc_fd_a_nohead_dan_none_nohead__crit_singular__sb_1e-7__b_1e-3__sl_-15__fcl_False__reg_svmo__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__1 --gpu-devices 3 --criterion singular  --switch-loss -15 --regularizer svmo --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 &

use_log=1 sing_beta=1e-3 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_nofc_fd_none_nohead_dan_none_nohead --save-dir supplement_resnet_log/resnet50_sf_nofc_fd_none_nohead_dan_none_nohead__crit_log_singular__sb_1e-3__b___sl_-35__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__0 --gpu-devices 4 --criterion singular  --switch-loss -35 --regularizer none --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 &

use_log=1 sing_beta=1e-3 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_nofc_fd_none_nohead_dan_none_nohead --save-dir supplement_resnet_log/resnet50_sf_nofc_fd_none_nohead_dan_none_nohead__crit_log_singular__sb_1e-3__b___sl_-25__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__0 --gpu-devices 5 --criterion singular  --switch-loss -25 --regularizer none --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 &

use_log=1 sing_beta=1e-3 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_nofc_fd_none_nohead_dan_none_nohead --save-dir supplement_resnet_log/resnet50_sf_nofc_fd_none_nohead_dan_none_nohead__crit_log_singular__sb_1e-3__b___sl_-15__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__0 --gpu-devices 6 --criterion singular  --switch-loss -15 --regularizer none --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 &

use_log=1 sing_beta=1e-4 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_nofc_fd_none_nohead_dan_none_nohead --save-dir supplement_resnet_log/resnet50_sf_nofc_fd_none_nohead_dan_none_nohead__crit_log_singular__sb_1e-4__b___sl_-35__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__0 --gpu-devices 7 --criterion singular  --switch-loss -35 --regularizer none --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 &

sleep 130m

use_log=1 sing_beta=1e-4 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_nofc_fd_none_nohead_dan_none_nohead --save-dir supplement_resnet_log/resnet50_sf_nofc_fd_none_nohead_dan_none_nohead__crit_log_singular__sb_1e-4__b___sl_-25__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__0 --gpu-devices 0 --criterion singular  --switch-loss -25 --regularizer none --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 &

use_log=1 sing_beta=1e-4 beta= nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_nofc_fd_none_nohead_dan_none_nohead --save-dir supplement_resnet_log/resnet50_sf_nofc_fd_none_nohead_dan_none_nohead__crit_log_singular__sb_1e-4__b___sl_-15__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__0 --gpu-devices 1 --criterion singular  --switch-loss -15 --regularizer none --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 &

sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_nofc_fd_ab_nohead_dan_cam_pam_nohead --save-dir supplement_resnet_log/resnet50_sf_nofc_fd_ab_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-7__b_1e-3__sl_-35__fcl_False__reg_svmo__dropout_none__dau_crop__pp_before,after,cam,pam__size_256__ep_60__ucg_False__cg_0.5__0 --gpu-devices 3 --criterion singular  --switch-loss -35 --regularizer svmo --dropout none --data-augment crop --penalty-position before,after,cam,pam  --clip-grad 0.5 &
sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_nofc_fd_ab_nohead_dan_cam_pam_nohead --save-dir supplement_resnet_log/resnet50_sf_nofc_fd_ab_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-7__b_1e-3__sl_-35__fcl_False__reg_svmo__dropout_none__dau_crop__pp_before,after,cam,pam__size_256__ep_60__ucg_False__cg_0.5__1 --gpu-devices 4 --criterion singular  --switch-loss -35 --regularizer svmo --dropout none --data-augment crop --penalty-position before,after,cam,pam  --clip-grad 0.5 &
sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_nofc_fd_ab_nohead_dan_cam_pam_nohead --save-dir supplement_resnet_log/resnet50_sf_nofc_fd_ab_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-7__b_1e-3__sl_-35__fcl_False__reg_svmo__dropout_none__dau_crop__pp_before,after,cam,pam__size_256__ep_60__ucg_False__cg_0.5__2 --gpu-devices 5 --criterion singular  --switch-loss -35 --regularizer svmo --dropout none --data-augment crop --penalty-position before,after,cam,pam  --clip-grad 0.5 &
sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_nofc_fd_ab_nohead_dan_cam_pam_nohead --save-dir supplement_resnet_log/resnet50_sf_nofc_fd_ab_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-7__b_1e-3__sl_-35__fcl_False__reg_svmo__dropout_none__dau_crop__pp_before,after,cam,pam__size_256__ep_60__ucg_False__cg_0.5__3 --gpu-devices 6 --criterion singular  --switch-loss -35 --regularizer svmo --dropout none --data-augment crop --penalty-position before,after,cam,pam  --clip-grad 0.5 &
sing_beta=1e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 3 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_nofc_fd_ab_nohead_dan_cam_pam_nohead --save-dir supplement_resnet_log/resnet50_sf_nofc_fd_ab_nohead_dan_cam_pam_nohead__crit_singular__sb_1e-7__b_1e-3__sl_-35__fcl_False__reg_svmo__dropout_none__dau_crop__pp_before,after,cam,pam__size_256__ep_60__ucg_False__cg_0.5__4 --gpu-devices 7 --criterion singular  --switch-loss -35 --regularizer svmo --dropout none --data-augment crop --penalty-position before,after,cam,pam  --clip-grad 0.5 &
