reg_const=1 flip_eval=1 dropout_reduction=1 sing_beta=1e-6 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501  -j 4 --height 384 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 200 --stepsize 20 50  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 64 --test-batch-size 100 -a resnet50_sf_tr6_fc1024_fd_ab_c_nohead_dan_cam_pam_nohead --save-dir 0219_trick_log/resnet50_sf_tr6_fc1024_fd_ab_nohead_dan_cam_pam_nohead__crit_singular__htri_sb_1e-6__b_1e-3__sl_-177__fcl_False__reg_const_svmo__dropout_incr__dau_crop,random-erase__pp_before,after,cam,pam,layer5__size_384__ep_200__lh_.1__dr__b64__m1.2__0 --gpu-devices 4,5 --criterion singular_htri  --switch-loss -177 --regularizer svmo --dropout incr --data-augment crop,random-erase  --penalty-position before,after,cam,pam,layer5  --lambda-htri 0.1 --margin 1.2 &


sleep 420m
ps aux | grep '4,5' | awk '{system("kill " $2)}'

reg_const=1 flip_eval=1 dropout_reduction=1 sing_beta=1e-6 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501  -j 4 --height 384 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 200 --stepsize 20 50  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 64 --test-batch-size 100 -a resnet50_sf_tr9_fc1024_fd_ab_c_nohead_dan_cam_pam_nohead --save-dir 0219_trick_log/resnet50_sf_tr9_fc1024_fd_ab_nohead_dan_cam_pam_nohead__crit_singular__htri_sb_1e-6__b_1e-3__sl_-177__fcl_False__reg_const_svmo__dropout_incr__dau_crop,random-erase__pp_before,after,cam,pam,layer5__size_384__ep_200__lh_.1__dr__b64__m1.2__0 --gpu-devices 4,5 --criterion singular_htri  --switch-loss -177 --regularizer svmo --dropout incr --data-augment crop,random-erase  --penalty-position before,after,cam,pam,layer5  --lambda-htri 0.1 --margin 1.2 &

---

head_col=2 reg_const=1 flip_eval=1 dropout_reduction=1 sing_beta=1e-6 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501  -j 4 --height 384 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 200 --stepsize 20 50  --open-layers classifier fc before_module pam_module cam_module sum_conv --fixbase-epoch 10  --train-batch-size 64 --test-batch-size 100 -a resnet50_sf_tr6_fc1024_fd_ab_c_nohead_dan_cam_pam_nohead --save-dir 0219_trick_log/resnet50_sf_tr6_fc1024_fd_ab_nohead_dan_cam_pam_nohead__crit_singular__htri_sb_1e-6__b_1e-3__sl_-177__fcl_False__reg_const_svmo__dropout_incr__dau_crop,random-erase__pp_before,after,cam,pam,layer5__size_384__ep_200__lh_.1__dr__b64__m1.2__hc_2_0 --gpu-devices 1,3 --criterion singular_htri  --switch-loss -179 --regularizer svmo --dropout incr --data-augment crop,random-erase  --penalty-position before,after,cam,pam,layer5  --lambda-htri 0.1 --margin 1.2 &

reg_deep=1 head_col=2 reg_const=1 flip_eval=1 dropout_reduction=1 sing_beta=1e-6 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501  -j 4 --height 384 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 200 --stepsize 20 50  --open-layers classifier fc before_module pam_module cam_module sum_conv --fixbase-epoch 10  --train-batch-size 64 --test-batch-size 100 -a resnet50_sf_tr6_fc1024_fd_ab_c_nohead_dan_cam_pam_nohead --save-dir 0219_trick_log/resnet50_sf_tr6_fc1024_fd_ab_nohead_dan_cam_pam_nohead__crit_singular__htri_sb_1e-6__b_1e-3__sl_-177__reg_const_svmo__dropout_incr__dau_crop,random-erase__pp_before,after,cam,pam,layer5__size_384__ep_200__lh_.1__dr__b64__m1.2__hc_2_rd_0 --gpu-devices 4,5 --criterion singular_htri  --switch-loss -179 --regularizer svmo --dropout incr --data-augment crop,random-erase  --penalty-position before,after,cam,pam,layer5  --lambda-htri 0.1 --margin 1.2 &

---

head_col=2 reg_const=1 flip_eval=1 dropout_reduction=1 sing_beta=1e-6 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501  -j 4 --height 384 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 200 --stepsize 20 50  --open-layers classifier fc before_module pam_module cam_module sum_conv --fixbase-epoch 10  --train-batch-size 64 --test-batch-size 100 -a resnet50_sf_tr6_fc512_fd_ab_c_nohead_dan_cam_pam_nohead --save-dir 0219_trick_log/resnet50_sf_tr6_fc512_fd_ab_c_nohead_dan_cam_pam_nohead__crit_singular__htri_sb_1e-6__b_1e-3__sl_-179__fcl_False__reg_const_svmo__dropout_incr__dau_crop,random-erase__pp_before,after,cam,pam,layer5__size_384__ep_200__lh_.1__dr__b64__m1.2__hc_2_0 --gpu-devices 1,2 --criterion singular_htri  --switch-loss -179 --regularizer svmo --dropout incr --data-augment crop,random-erase  --penalty-position before,after,cam,pam,layer5  --lambda-htri 0.1 --margin 1.2 &

head_col=4 reg_const=1 flip_eval=1 dropout_reduction=1 sing_beta=1e-6 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501  -j 4 --height 384 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 200 --stepsize 20 50  --open-layers classifier fc before_module pam_module cam_module sum_conv --fixbase-epoch 10  --train-batch-size 64 --test-batch-size 100 -a resnet50_sf_tr6_fc512_fd_ab_c_nohead_dan_cam_pam_nohead --save-dir 0219_trick_log/resnet50_sf_tr6_fc512_fd_ab_c_nohead_dan_cam_pam_nohead__crit_singular__htri_sb_1e-6__b_1e-3__sl_-179__fcl_False__reg_const_svmo__dropout_incr__dau_crop,random-erase__pp_before,after,cam,pam,layer5__size_384__ep_200__lh_.1__dr__b64__m1.2__hc_4_0 --gpu-devices 3,4 --criterion singular_htri  --switch-loss -179 --regularizer svmo --dropout incr --data-augment crop,random-erase  --penalty-position before,after,cam,pam,layer5  --lambda-htri 0.1 --margin 1.2 &

head_col=2 reg_const=1 flip_eval=1 dropout_reduction=1 sing_beta=1e-6 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501  -j 4 --height 384 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 200 --stepsize 20 50  --open-layers classifier fc before_module1 pam_module1 cam_module1 sum_conv1 --fixbase-epoch 10  --train-batch-size 64 --test-batch-size 100 -a resnet50_sf_tr9_fc1024_fd_ab_c_nohead_dan_cam_pam_nohead --save-dir 0219_trick_log/resnet50_sf_tr9_fc1024_fd_ab_c_nohead_dan_cam_pam_nohead__crit_singular__htri_sb_1e-6__b_1e-3__sl_-179__fcl_False__reg_const_svmo__dropout_incr__dau_crop,random-erase__pp_before,after,cam,pam,layer5__size_384__ep_200__lh_.1__dr__b64__m1.2__hc_2_0 --gpu-devices 3,4 --criterion singular_htri  --switch-loss -179 --regularizer svmo --dropout incr --data-augment crop,random-erase  --penalty-position before,after,cam,pam,layer5  --lambda-htri 0.1 --margin 1.2 &

head_col=2 reg_const=1 flip_eval=1 dropout_reduction=1 sing_beta=8e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501  -j 4 --height 384 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 200 --stepsize 20 50  --open-layers classifier fc before_module1 pam_module1 cam_module1 sum_conv1 --fixbase-epoch 10  --train-batch-size 64 --test-batch-size 100 -a resnet50_sf_tr10_fc1024_fd_ab_c_nohead_dan_cam_pam_nohead --save-dir 0219_trick_log/resnet50_sf_tr10_fc1024_fd_ab_c_nohead_dan_cam_pam_nohead__crit_singular__htri_sb_1e-6__b_1e-3__sl_-179__fcl_False__reg_const_svmo__dropout_incr__dau_crop,random-erase__pp_before,after,cam,pam,layer5__size_384__ep_200__lh_.1__dr__b64__m1.2__hc_2_0 --gpu-devices 1,2 --criterion singular_htri  --switch-loss -179 --regularizer svmo --dropout incr --data-augment crop,random-erase  --penalty-position before,after,cam,pam,layer5  --lambda-htri 0.1 --margin 1.2 &

---

head_col=2 reg_const=1 flip_eval=1 dropout_reduction=1 sing_beta=1e-6 beta=1e-3 part_num=3 python train_reg_crit.py --root data -s market1501 -t market1501  -j 4 --height 384 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 200 --stepsize 20 50  --open-layers classifier fc before_module1 pam_module1 cam_module1 sum_conv1 --fixbase-epoch 0  --train-batch-size 64 --test-batch-size 100 -a resnet50_sf_tr9_fc1024_fd_ab_c_nohead_dan_cam_pam_nohead --save-dir 0219_trick_log/resnet50_sf_tr9_fc1024_fd_ab_c_nohead_dan_cam_pam_nohead__crit_singular__htri_sb_1e-6__b_1e-3__sl_-179__fcl_False__reg_const_svmo__dropout_incr__dau_crop,random-erase__pp_before,after,cam,pam,layer5__size_384__ep_200__lh_.1__dr__b64__m1.2__hc_2_p3_0 --gpu-devices 0,1,2 --criterion singular_htri  --switch-loss 0 --regularizer svmo --dropout incr --data-augment crop,random-erase  --penalty-position before,after,cam,pam,layer5  --lambda-htri 0.1 --margin 1.2

head_col=2 reg_const=1 flip_eval=1 dropout_reduction=1 sing_beta=1e-6 beta=1e-3 part_num=3 nohup python train_reg_crit.py --root data -s market1501 -t market1501  -j 4 --height 384 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 200 --stepsize 20 50  --open-layers classifier fc before_module1 pam_module1 cam_module1 sum_conv1 --fixbase-epoch 10  --train-batch-size 64 --test-batch-size 100 -a resnet50_sf_tr10_fc1024_fd_ab_c_nohead_dan_cam_pam_nohead --save-dir 0219_trick_log/resnet50_sf_tr10_fc1024_fd_ab_c_nohead_dan_cam_pam_nohead__crit_singular__htri_sb_1e-6__b_1e-3__sl_-179__fcl_False__reg_const_svmo__dropout_incr__dau_crop,random-erase__pp_before,after,cam,pam,layer5__size_384__ep_200__lh_.1__dr__b64__m1.2__hc_2_p3_0 --gpu-devices 1,2,3,4 --criterion singular_htri  --switch-loss -179 --regularizer svmo --dropout incr --data-augment crop,random-erase  --penalty-position before,after,cam,pam,layer5  --lambda-htri 0.1 --margin 1.2 &

head_col=2 reg_const=1 flip_eval=1 dropout_reduction=1 sing_beta=8e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501  -j 4 --height 384 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 200 --stepsize 20 40  --open-layers classifier fc before_module1 pam_module1 cam_module1 sum_conv1 --fixbase-epoch 10  --train-batch-size 64 --test-batch-size 100 -a resnet50_sf_tr10_fc1024_fd_ab_c_nohead_dan_cam_pam_nohead --save-dir 0219_trick_log/resnet50_sf_tr10_fc1024_fd_ab_c_nohead_dan_cam_pam_nohead__crit_singular__htri_sb_8e-7__b_1e-3__sl_-179__fcl_False__reg_const_svmo__dropout_incr__dau_crop,random-erase__pp_before,after,cam,pam,layer5__size_384__ep_200__lh_.1__dr__b64__m1.2__hc_2_0 --gpu-devices 1,2 --criterion singular_htri  --switch-loss -179 --regularizer svmo --dropout incr --data-augment crop,random-erase  --penalty-position before,after,cam,pam,layer5  --lambda-htri 0.1 --margin 1.2 &

head_col=1 reg_const=1 flip_eval=1 dropout_reduction=1 sing_beta=8e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501  -j 4 --height 384 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 200 --stepsize 20 40  --open-layers classifier fc before_module1 pam_module1 cam_module1 sum_conv1 --fixbase-epoch 10  --train-batch-size 64 --test-batch-size 100 -a resnet50_sf_tr10_fc1024_fd_ab_c_nohead_dan_cam_pam_nohead --save-dir 0219_trick_log/resnet50_sf_tr10_fc1024_fd_ab_c_nohead_dan_cam_pam_nohead__crit_singular__htri_sb_8e-7__b_1e-3__sl_-179__fcl_False__reg_const_svmo__dropout_incr__dau_crop,random-erase__pp_before,after,cam,pam,layer5__size_384__ep_200__lh_.1__dr__b64__m1.2__hc_1_0 --gpu-devices 3,4 --criterion singular_htri  --switch-loss -179 --regularizer svmo --dropout incr --data-augment crop,random-erase  --penalty-position before,after,cam,pam,layer5  --lambda-htri 0.1 --margin 1.2 &

---

head_col=2 reg_const=1 flip_eval=1 dropout_reduction=1 sing_beta=1e-6 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501  -j 4 --height 384 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 200 --stepsize 20 50  --open-layers classifier fc before_module1 pam_module1 cam_module1 sum_conv1 before_module2 pam_module2 cam_module2 sum_conv2 --fixbase-epoch 10  --train-batch-size 64 --test-batch-size 100 -a resnet50_sf_tr11_fc1024_fd_ab_c_nohead_dan_cam_pam_nohead --save-dir 0219_trick_log/resnet50_sf_tr11_fc1024_fd_ab_c_nohead_dan_cam_pam_nohead__crit_singular__htri_sb_1e-6__b_1e-3__sl_-179__fcl_False__reg_const_svmo__dropout_incr__dau_crop,random-erase__pp_before,after,cam,pam,layer5__size_384__ep_200__lh_.1__dr__b64__m1.2__hc_2_0 --gpu-devices 3,4 --criterion singular_htri  --switch-loss -179 --regularizer svmo --dropout incr --data-augment crop,random-erase  --penalty-position before,after,cam,pam,layer5  --lambda-htri 0.1 --margin 1.2 &

head_col=2 reg_const=1 flip_eval=1 dropout_reduction=1 sing_beta=8e-7 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501  -j 4 --height 384 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 200 --stepsize 20 50  --open-layers classifier fc before_module1 pam_module1 cam_module1 sum_conv1 before_module2 pam_module2 cam_module2 sum_conv2 --fixbase-epoch 10  --train-batch-size 64 --test-batch-size 100 -a resnet50_sf_tr12_fc1024_fd_ab_c_nohead_dan_cam_pam_nohead --save-dir 0219_trick_log/resnet50_sf_tr12_fc1024_fd_ab_c_nohead_dan_cam_pam_nohead__crit_singular__htri_sb_1e-6__b_1e-3__sl_-179__fcl_False__reg_const_svmo__dropout_incr__dau_crop,random-erase__pp_before,after,cam,pam,layer5__size_384__ep_200__lh_.1__dr__b64__m1.2__hc_2_0 --gpu-devices 1,2 --criterion singular_htri  --switch-loss -179 --regularizer svmo --dropout incr --data-augment crop,random-erase  --penalty-position before,after,cam,pam,layer5  --lambda-htri 0.1 --margin 1.2 &
