head_col=2 reg_const=1 flip_eval=1 dropout_reduction=1 sing_beta=1e-6 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501  -j 4 --height 384 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 200 --stepsize 20 40  --open-layers classifier fc before_module1 pam_module1 cam_module1 sum_conv1 --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_abd_fc1024_fd_none_nohead_dan_none_nohead --save-dir 0225_abd_log/ow/resnet50_abd_fd_none_nohead_dan_none_nohead__crit__xent_sb_1e-6__b_1e-3__sl_0__fcl_False__reg_const_svmo__dropout_none__dau_crop__pp_before,after,cam,pam,layer5__size_384__ep_200__lh_.1__dr__b32__m1.2__hc_2_p2 --gpu-devices 1,2 --criterion xent  --regularizer svmo --dropout none --data-augment crop  --penalty-position before,after,cam,pam,layer5  --lambda-htri 0.1 --margin 1.2 &

head_col=2 reg_const=1 flip_eval=1 dropout_reduction=1 sing_beta=1e-6 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501  -j 4 --height 384 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 200 --stepsize 20 40  --open-layers classifier fc before_module1 pam_module1 cam_module1 sum_conv1 --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_abd_fc1024_fd_none_nohead_dan_none_nohead --save-dir 0225_abd_log/of/resnet50_abd_fd_none_nohead_dan_none_nohead__crit_singular__sb_1e-6__b_1e-3__sl_-177__fcl_False__reg_const_svmo__dropout_none__dau_crop__pp_after,layer5__size_384__ep_200__lh_.1__dr__b32__m1.2__hc_2_p2 --gpu-devices 3,4 --criterion singular --switch-loss -177 --regularizer none --dropout none --data-augment crop  --penalty-position after,layer5  --lambda-htri 0.1 --margin 1.2 &

part_num=1 head_col=2 reg_const=1 flip_eval=1 dropout_reduction=1 sing_beta=1e-6 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501  -j 4 --height 384 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 200 --stepsize 20 40  --open-layers classifier fc before_module1 pam_module1 cam_module1 sum_conv1 --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_abd_fc1024_fd_none_nohead_dan_none_nohead --save-dir 0225_abd_log/ow/resnet50_abd_fd_none_nohead_dan_none_nohead__crit__xent_sb_1e-6__b_1e-3__sl_0__fcl_False__reg_const_svmo__dropout_none__dau_crop__pp_before,after,cam,pam,layer5__size_384__ep_200__lh_.1__dr__b32__m1.2__hc_2_p1 --gpu-devices 0,5 --criterion xent  --regularizer svmo --dropout none --data-augment crop  --penalty-position before,after,cam,pam,layer5  --lambda-htri 0.1 --margin 1.2 &

---

head_col=2 reg_const=1 flip_eval=1 dropout_reduction=1 sing_beta=1e-6 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501  -j 4 --height 384 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 200 --stepsize 20 40  --open-layers classifier fc before_module1 pam_module1 cam_module1 sum_conv1 --fixbase-epoch 10  --train-batch-size 64 --test-batch-size 100 -a resnet50_sf_abd_fc1024_fd_none_nohead_dan_none_nohead --save-dir 0225_abd_log/owof/resnet50_abd_fd_none_nohead_dan_none_nohead__crit_singular__sb_1e-6__b_1e-3__sl_-177__fcl_False__reg_const_svmo__dropout_none__dau_crop,random-erase__pp_after,layer5__size_384__ep_200__lh_.1__dr__b64__m1.2__hc_2_p2 --gpu-devices 0,1 --criterion singular --switch-loss -177 --regularizer svmo --dropout none --data-augment crop,random-erase  --penalty-position after,layer5  --lambda-htri 0.1 --margin 1.2 &

head_col=2 reg_const=1 flip_eval=1 dropout_reduction=1 sing_beta=1e-6 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501  -j 4 --height 384 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 200 --stepsize 20 40  --open-layers classifier fc before_module1 pam_module1 cam_module1 sum_conv1 --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_abd_fc1024_fd_none_nohead_dan_none_nohead --save-dir 0225_abd_log/owof/resnet50_abd_fd_none_nohead_dan_none_nohead__crit_singular__sb_1e-6__b_1e-3__sl_-177__fcl_False__reg_const_svmo__dropout_none__dau_crop__pp_after,layer5__size_384__ep_200__lh_.1__dr__b32__m1.2__hc_2_p2 --gpu-devices 2,3 --criterion singular --switch-loss -177 --regularizer svmo --dropout none --data-augment crop  --penalty-position after,layer5  --lambda-htri 0.1 --margin 1.2 &

head_col=2 reg_const=1 flip_eval=1 dropout_reduction=1 sing_beta=1e-6 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501  -j 4 --height 384 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 200 --stepsize 20 40  --open-layers classifier fc before_module1 pam_module1 cam_module1 sum_conv1 --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_abd_fc1024_fd_none_nohead_dan_cam_pam_nohead --save-dir 0225_abd_log/campam/resnet50_abd_fd_none_nohead_dan_cam_pam_nohead__crit_xemt__sb_1e-6__b_1e-3__sl_-177__fcl_False__reg_const_none__dropout_none__dau_crop__pp_after,layer5__size_384__ep_200__lh_.1__dr__b32__m1.2__hc_2_p2 --gpu-devices 4,5 --criterion xent --switch-loss -177 --regularizer none --dropout none --data-augment crop  --penalty-position after,layer5  --lambda-htri 0.1 --margin 1.2 &

---

head_col=2 reg_const=1 flip_eval=1 dropout_reduction=1 sing_beta=1e-6 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501  -j 4 --height 384 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 200 --stepsize 20 40  --open-layers classifier fc before_module1 pam_module1 cam_module1 sum_conv1 --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_abd_fc1024_fd_abc_nohead_dan_none_nohead --save-dir 0225_abd_log/sabd/resnet50_abd_fd_abc_nohead_dan_none_nohead__crit_xent__sb_1e-6__b_1e-3__sl_-177__fcl_False__reg_const_none__dropout_none__dau_none__pp_layer5__size_384__ep_200__lh_.1__dr__b32__m1.2__hc_2_p2 --gpu-devices 0,1 --criterion singular --switch-loss -177 --regularizer none --dropout none --data-augment none  --penalty-position layer5  --lambda-htri 0.1 --margin 1.2 &

head_col=2 reg_const=1 flip_eval=1 dropout_reduction=1 sing_beta=1e-6 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501  -j 4 --height 384 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 200 --stepsize 20 40  --open-layers classifier fc before_module1 pam_module1 cam_module1 sum_conv1 --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_abd_fc1024_fd_none_nohead_dan_cam_pam_nohead --save-dir 0225_abd_log/dabd/resnet50_abd_fd_none_nohead_dan_cam_pam_nohead__crit_xent__sb_1e-6__b_1e-3__sl_-177__fcl_False__reg_const_none__dropout_incr__dau_crop,random-erase__pp_layer5__size_384__ep_200__lh_.1__dr__b32__m1.2__hc_2_p2 --gpu-devices 2,4 --criterion singular --switch-loss -177 --regularizer none --dropout incr --data-augment crop,random-erase  --penalty-position before,after,cam,pam  --lambda-htri 0.1 --margin 1.2 &


head_col=2 reg_const=1 flip_eval=1 dropout_reduction=1 sing_beta=1e-6 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501  -j 4 --height 384 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 200 --stepsize 20 40  --open-layers classifier fc before_module1 pam_module1 cam_module1 sum_conv1 --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_sf_abd_fc1024_fd_none_nohead_dan_none_nohead --save-dir 0225_abd_log/baseline/resnet50_abd_fd_none_nohead_dan_none_nohead__crit_xent__sb_1e-6__b_1e-3__sl_-177__fcl_False__reg_const_none__dropout_none__dau_crop__pp_layer5__size_384__ep_200__lh_.1__dr__b32__m1.2__hc_2_p2 --gpu-devices 0,1 --criterion xent --switch-loss -177 --regularizer none --dropout none --data-augment crop  --penalty-position before,after,cam,pam  --lambda-htri 0.1 --margin 1.2 &


head_col=2 reg_const=1 flip_eval=1 dropout_reduction=1 sing_beta=1e-6 beta=1e-3 nohup python train_reg_crit.py --root data -s market1501 -t market1501  -j 4 --height 384 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 200 --stepsize 20 40  --open-layers classifier fc before_module1 pam_module1 cam_module1 sum_conv1 --fixbase-epoch 10  --train-batch-size 64 --test-batch-size 100 -a resnet50_sf_abd_fc1024_fd_none_nohead_dan_none_nohead --save-dir 0225_abd_log/ow/resnet50_abd_fd_none_nohead_dan_none_nohead__crit__xent_sb_1e-6__b_1e-3__sl_0__fcl_False__reg_const_svmo__dropout_incr__dau_crop__pp_before,after,cam,pam,layer5__size_384__ep_200__lh_.1__dr__b64__m1.2__hc_2_p2 --gpu-devices 3,4 --criterion xent  --regularizer svmo --dropout incr --data-augment crop  --penalty-position before,after,cam,pam,layer5  --lambda-htri 0.1 --margin 1.2 &
