 beta=1e-7 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_nofc_fd_none_nohead_dan_none_nohead --save-dir 0309_spectral_log/resnet50_nofc_fd_none_nohead_dan_none_nohead__crit_batch_spectral__sb___b_1e-7__sl_0__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__rs --gpu-devices 4 --criterion batch_spectral  --switch-loss 0 --regularizer none --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 --train-sampler RandomIdentitySampler &

 beta=1e-6 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_nofc_fd_none_nohead_dan_none_nohead --save-dir 0309_spectral_log/resnet50_nofc_fd_none_nohead_dan_none_nohead__crit_batch_spectral__sb___b_1e-6__sl_0__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__rs --gpu-devices 5 --criterion batch_spectral  --switch-loss 0 --regularizer none --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 --train-sampler RandomIdentitySampler &

 beta=1e-7 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_nofc_fd_none_nohead_dan_none_nohead --save-dir 0309_spectral_log/resnet50_nofc_fd_none_nohead_dan_none_nohead__crit_batch_spectral__sb___b_1e-7__sl_-35__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__rs --gpu-devices 6 --criterion batch_spectral  --switch-loss -35 --regularizer none --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 --train-sampler RandomIdentitySampler &

 beta=1e-6 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_nofc_fd_none_nohead_dan_none_nohead --save-dir 0309_spectral_log/resnet50_nofc_fd_none_nohead_dan_none_nohead__crit_batch_spectral__sb___b_1e-6__sl_-35__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__rs --gpu-devices 7 --criterion batch_spectral  --switch-loss -35 --regularizer none --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 --train-sampler RandomIdentitySampler &

sleep 90m


 beta=5e-7 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_nofc_fd_none_nohead_dan_none_nohead --save-dir 0309_spectral_log/resnet50_nofc_fd_none_nohead_dan_none_nohead__crit_batch_spectral__sb___b_5e-7__sl_0__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__rs --gpu-devices 4 --criterion batch_spectral  --switch-loss 0 --regularizer none --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 --train-sampler RandomIdentitySampler &

 beta=5e-6 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_nofc_fd_none_nohead_dan_none_nohead --save-dir 0309_spectral_log/resnet50_nofc_fd_none_nohead_dan_none_nohead__crit_batch_spectral__sb___b_5e-6__sl_0__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__rs --gpu-devices 5 --criterion batch_spectral  --switch-loss 0 --regularizer none --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 --train-sampler RandomIdentitySampler &

 beta=5e-7 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_nofc_fd_none_nohead_dan_none_nohead --save-dir 0309_spectral_log/resnet50_nofc_fd_none_nohead_dan_none_nohead__crit_batch_spectral__sb___b_5e-7__sl_-35__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__rs --gpu-devices 6 --criterion batch_spectral  --switch-loss -35 --regularizer none --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 --train-sampler RandomIdentitySampler &

 beta=5e-6 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_nofc_fd_none_nohead_dan_none_nohead --save-dir 0309_spectral_log/resnet50_nofc_fd_none_nohead_dan_none_nohead__crit_batch_spectral__sb___b_5e-6__sl_-35__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__rs --gpu-devices 7 --criterion batch_spectral  --switch-loss -35 --regularizer none --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 --train-sampler RandomIdentitySampler &

sleep 90m




 beta=1e-5 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_nofc_fd_none_nohead_dan_none_nohead --save-dir 0309_spectral_log/resnet50_nofc_fd_none_nohead_dan_none_nohead__crit_batch_spectral__sb___b_1e-5__sl_0__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__rs --gpu-devices 4 --criterion batch_spectral  --switch-loss 0 --regularizer none --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 --train-sampler RandomIdentitySampler &

 beta=1e-4 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_nofc_fd_none_nohead_dan_none_nohead --save-dir 0309_spectral_log/resnet50_nofc_fd_none_nohead_dan_none_nohead__crit_batch_spectral__sb___b_1e-4__sl_0__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__rs --gpu-devices 5 --criterion batch_spectral  --switch-loss 0 --regularizer none --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 --train-sampler RandomIdentitySampler &

 beta=1e-5 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_nofc_fd_none_nohead_dan_none_nohead --save-dir 0309_spectral_log/resnet50_nofc_fd_none_nohead_dan_none_nohead__crit_batch_spectral__sb___b_1e-5__sl_-35__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__rs --gpu-devices 6 --criterion batch_spectral  --switch-loss -35 --regularizer none --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 --train-sampler RandomIdentitySampler &

 beta=1e-4 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_nofc_fd_none_nohead_dan_none_nohead --save-dir 0309_spectral_log/resnet50_nofc_fd_none_nohead_dan_none_nohead__crit_batch_spectral__sb___b_1e-4__sl_-35__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__rs --gpu-devices 7 --criterion batch_spectral  --switch-loss -35 --regularizer none --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 --train-sampler RandomIdentitySampler &


sleep 90m


 beta=1e-5 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_nofc_fd_none_nohead_dan_none_nohead --save-dir 0309_spectral_log/resnet50_nofc_fd_none_nohead_dan_none_nohead__crit_batch_spectral__sb___b_1e-5__sl_0__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__rs --gpu-devices 4 --criterion batch_spectral  --switch-loss 0 --regularizer none --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 --train-sampler RandomIdentitySampler &

 beta=1e-4 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_nofc_fd_none_nohead_dan_none_nohead --save-dir 0309_spectral_log/resnet50_nofc_fd_none_nohead_dan_none_nohead__crit_batch_spectral__sb___b_1e-4__sl_0__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__rs --gpu-devices 5 --criterion batch_spectral  --switch-loss 0 --regularizer none --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 --train-sampler RandomIdentitySampler &

 beta=1e-5 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_nofc_fd_none_nohead_dan_none_nohead --save-dir 0309_spectral_log/resnet50_nofc_fd_none_nohead_dan_none_nohead__crit_batch_spectral__sb___b_1e-5__sl_-35__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__rs --gpu-devices 6 --criterion batch_spectral  --switch-loss -35 --regularizer none --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 --train-sampler RandomIdentitySampler &

 beta=1e-4 nohup python train_reg_crit.py --root data -s market1501 -t market1501 -j 4 --height 256 --width 128 --eval-freq 1 --optim adam --label-smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40  --open-layers classifier fc --fixbase-epoch 10  --train-batch-size 32 --test-batch-size 100 -a resnet50_nofc_fd_none_nohead_dan_none_nohead --save-dir 0309_spectral_log/resnet50_nofc_fd_none_nohead_dan_none_nohead__crit_batch_spectral__sb___b_1e-4__sl_-35__fcl_False__reg_none__dropout_none__dau_crop__pp_before__size_256__ep_60__ucg_False__cg_0.5__rs --gpu-devices 7 --criterion batch_spectral  --switch-loss -35 --regularizer none --dropout none --data-augment crop --penalty-position before  --clip-grad 0.5 --train-sampler RandomIdentitySampler &
