part_num=1 nohup python train_reg_crit.py -s market1501 -t market1501 --eval-freq 5 --flip-eval --label-smooth --criterion xent --lambda-htri 0.1  --dropout none --data-augment crop --regularizer none --margin 1.2 --train-batch-size 32 --switch-loss -178 --penalty-position before,after,cam,pam,layer5 --height 384 --width 128 --fixbase-epoch 10 --optim adam --lr 0.0003 --stepsize 20 40 --max-epoch 60 --save-dir abl_market_log/baseline --arch resnet50_abl_fc1024_fd_none_nohead_dan_none_nohead --gpu-devices 1&

part_num=1 nohup python train_reg_crit.py -s market1501 -t market1501 --eval-freq 5 --flip-eval --label-smooth --criterion xent --lambda-htri 0.1  --dropout none --data-augment crop,random-erase --regularizer none --margin 1.2 --train-batch-size 32 --switch-loss -178 --penalty-position before,after,cam,pam,layer5 --height 384 --width 128 --fixbase-epoch 10 --optim adam --lr 0.0003 --stepsize 20 40 --max-epoch 60 --save-dir abl_market_log/baseline_re --arch resnet50_abl_fc1024_fd_none_nohead_dan_none_nohead --gpu-devices 2&

part_num=1 nohup python train_reg_crit.py -s market1501 -t market1501 --eval-freq 5 --flip-eval --label-smooth --criterion xent --lambda-htri 0.1  --dropout incr --data-augment crop --regularizer none --margin 1.2 --train-batch-size 32 --switch-loss -178 --penalty-position before,after,cam,pam,layer5 --height 384 --width 128 --fixbase-epoch 10 --optim adam --lr 0.0003 --stepsize 20 40 --max-epoch 60 --save-dir abl_market_log/baseline_dropout --arch resnet50_abl_fc1024_fd_none_nohead_dan_none_nohead --gpu-devices 3&

part_num=1 tb=1 nohup python train_reg_crit.py -s market1501 -t market1501 --eval-freq 5 --flip-eval --label-smooth --criterion xent --lambda-htri 0.1  --dropout none --data-augment crop --regularizer none --margin 1.2 --train-batch-size 32 --switch-loss -178 --penalty-position before,after,cam,pam,layer5 --height 384 --width 128 --fixbase-epoch 10 --optim adam --lr 0.0003 --stepsize 20 40 --max-epoch 60 --save-dir abl_market_log/baseline_tb --arch resnet50_abl_fc1024_fd_none_nohead_dan_none_nohead --gpu-devices 4&

part_num=2 nohup python train_reg_crit.py -s market1501 -t market1501 --eval-freq 5 --flip-eval --label-smooth --criterion xent --lambda-htri 0.1  --dropout none --data-augment crop --regularizer none --margin 1.2 --train-batch-size 32 --switch-loss -178 --penalty-position before,after,cam,pam,layer5 --height 384 --width 128 --fixbase-epoch 10 --optim adam --lr 0.0003 --stepsize 20 40 --max-epoch 60 --save-dir abl_market_log/baseline_p2 --arch resnet50_abl_fc1024_fd_none_nohead_dan_none_nohead --gpu-devices 5&

part_num=1 nohup python train_reg_crit.py -s market1501 -t market1501 --eval-freq 5 --flip-eval --label-smooth --criterion xent --lambda-htri 0.1  --dropout none --data-augment crop --regularizer none --margin 1.2 --train-batch-size 32 --switch-loss -178 --penalty-position before,after,cam,pam,layer5 --height 384 --width 128 --fixbase-epoch 10 --optim adam --lr 0.0003 --stepsize 20 40 --max-epoch 60 --save-dir abl_market_log/baseline_scam --arch resnet50_abl_fc1024_fd_abc_nohead_dan_none_nohead --gpu-devices 6&

sleep 150m

part_num=1 nohup python train_reg_crit.py -s market1501 -t market1501 --eval-freq 5 --flip-eval --label-smooth --criterion xent --lambda-htri 0.1  --dropout none --data-augment crop --regularizer none --margin 1.2 --train-batch-size 32 --switch-loss -178 --penalty-position before,after,cam,pam,layer5 --height 384 --width 128 --fixbase-epoch 10 --optim adam --lr 0.0003 --stepsize 20 40 --max-epoch 60 --save-dir abl_market_log/baseline_dcam --arch resnet50_abl_fc1024_fd_none_nohead_dan_cam_nohead --gpu-devices 1&

part_num=1 nohup python train_reg_crit.py -s market1501 -t market1501 --eval-freq 5 --flip-eval --label-smooth --criterion xent --lambda-htri 0.1  --dropout none --data-augment crop --regularizer none --margin 1.2 --train-batch-size 32 --switch-loss -178 --penalty-position before,after,cam,pam,layer5 --height 384 --width 128 --fixbase-epoch 10 --optim adam --lr 0.0003 --stepsize 20 40 --max-epoch 60 --save-dir abl_market_log/baseline_pam --arch resnet50_abl_fc1024_fd_none_nohead_dan_pam_nohead --gpu-devices 2&

sing_beta=1e-6 part_num=1 nohup python train_reg_crit.py -s market1501 -t market1501 --eval-freq 5 --flip-eval --label-smooth --criterion singular --lambda-htri 0.1  --dropout none --data-augment crop --regularizer none --margin 1.2 --train-batch-size 32 --switch-loss -35 --penalty-position after --height 384 --width 128 --fixbase-epoch 10 --optim adam --lr 0.0003 --stepsize 20 40 --max-epoch 60 --save-dir abl_market_log/baseline_of --arch resnet50_abl_fc1024_fd_none_nohead_dan_none_nohead --gpu-devices 3&

beta=1e-3 part_num=1 nohup python train_reg_crit.py -s market1501 -t market1501 --eval-freq 5 --flip-eval --label-smooth --criterion xent --lambda-htri 0.1  --dropout none --data-augment none --regularizer svmo --margin 1.2 --train-batch-size 32 --switch-loss -178 --penalty-position after --height 384 --width 128 --fixbase-epoch 10 --optim adam --lr 0.0003 --stepsize 20 40 --max-epoch 60 --save-dir abl_market_log/baseline_ow --arch resnet50_abl_fc1024_fd_none_nohead_dan_none_nohead --gpu-devices 4&

sleep 180m

part_num=1 nohup python train_reg_crit.py -s dukemtmcreid -t dukemtmcreid --eval-freq 5 --flip-eval --label-smooth --criterion xent --lambda-htri 0.1  --dropout none --data-augment crop --regularizer none --margin 1.2 --train-batch-size 32 --switch-loss -178 --penalty-position before,after,cam,pam,layer5 --height 384 --width 128 --fixbase-epoch 10 --optim adam --lr 0.0003 --stepsize 20 40 --max-epoch 60 --save-dir abl_duke_log/baseline --arch resnet50_abl_fc1024_fd_none_nohead_dan_none_nohead --gpu-devices 1&

part_num=1 nohup python train_reg_crit.py -s dukemtmcreid -t dukemtmcreid --eval-freq 5 --flip-eval --label-smooth --criterion xent --lambda-htri 0.1  --dropout none --data-augment crop,random-erase --regularizer none --margin 1.2 --train-batch-size 32 --switch-loss -178 --penalty-position before,after,cam,pam,layer5 --height 384 --width 128 --fixbase-epoch 10 --optim adam --lr 0.0003 --stepsize 20 40 --max-epoch 60 --save-dir abl_duke_log/baseline_re --arch resnet50_abl_fc1024_fd_none_nohead_dan_none_nohead --gpu-devices 2&

part_num=1 nohup python train_reg_crit.py -s dukemtmcreid -t dukemtmcreid --eval-freq 5 --flip-eval --label-smooth --criterion xent --lambda-htri 0.1  --dropout incr --data-augment crop --regularizer none --margin 1.2 --train-batch-size 32 --switch-loss -178 --penalty-position before,after,cam,pam,layer5 --height 384 --width 128 --fixbase-epoch 10 --optim adam --lr 0.0003 --stepsize 20 40 --max-epoch 60 --save-dir abl_duke_log/baseline_dropout --arch resnet50_abl_fc1024_fd_none_nohead_dan_none_nohead --gpu-devices 3&

part_num=1 tb=1 nohup python train_reg_crit.py -s dukemtmcreid -t dukemtmcreid --eval-freq 5 --flip-eval --label-smooth --criterion xent --lambda-htri 0.1  --dropout none --data-augment crop --regularizer none --margin 1.2 --train-batch-size 32 --switch-loss -178 --penalty-position before,after,cam,pam,layer5 --height 384 --width 128 --fixbase-epoch 10 --optim adam --lr 0.0003 --stepsize 20 40 --max-epoch 60 --save-dir abl_duke_log/baseline_tb --arch resnet50_abl_fc1024_fd_none_nohead_dan_none_nohead --gpu-devices 4&

part_num=2 nohup python train_reg_crit.py -s dukemtmcreid -t dukemtmcreid --eval-freq 5 --flip-eval --label-smooth --criterion xent --lambda-htri 0.1  --dropout none --data-augment crop --regularizer none --margin 1.2 --train-batch-size 32 --switch-loss -178 --penalty-position before,after,cam,pam,layer5 --height 384 --width 128 --fixbase-epoch 10 --optim adam --lr 0.0003 --stepsize 20 40 --max-epoch 60 --save-dir abl_duke_log/baseline_p2 --arch resnet50_abl_fc1024_fd_none_nohead_dan_none_nohead --gpu-devices 5&

part_num=1 nohup python train_reg_crit.py -s dukemtmcreid -t dukemtmcreid --eval-freq 5 --flip-eval --label-smooth --criterion xent --lambda-htri 0.1  --dropout none --data-augment crop --regularizer none --margin 1.2 --train-batch-size 32 --switch-loss -178 --penalty-position before,after,cam,pam,layer5 --height 384 --width 128 --fixbase-epoch 10 --optim adam --lr 0.0003 --stepsize 20 40 --max-epoch 60 --save-dir abl_duke_log/baseline_scam --arch resnet50_abl_fc1024_fd_abc_nohead_dan_none_nohead --gpu-devices 6&

sleep 210m

part_num=1 nohup python train_reg_crit.py -s dukemtmcreid -t dukemtmcreid --eval-freq 5 --flip-eval --label-smooth --criterion xent --lambda-htri 0.1  --dropout none --data-augment crop --regularizer none --margin 1.2 --train-batch-size 32 --switch-loss -178 --penalty-position before,after,cam,pam,layer5 --height 384 --width 128 --fixbase-epoch 10 --optim adam --lr 0.0003 --stepsize 20 40 --max-epoch 60 --save-dir abl_duke_log/baseline_dcam --arch resnet50_abl_fc1024_fd_none_nohead_dan_cam_nohead --gpu-devices 1&

part_num=1 nohup python train_reg_crit.py -s dukemtmcreid -t dukemtmcreid --eval-freq 5 --flip-eval --label-smooth --criterion xent --lambda-htri 0.1  --dropout none --data-augment crop --regularizer none --margin 1.2 --train-batch-size 32 --switch-loss -178 --penalty-position before,after,cam,pam,layer5 --height 384 --width 128 --fixbase-epoch 10 --optim adam --lr 0.0003 --stepsize 20 40 --max-epoch 60 --save-dir abl_duke_log/baseline_pam --arch resnet50_abl_fc1024_fd_none_nohead_dan_pam_nohead --gpu-devices 2&

sing_beta=1e-6 part_num=1 nohup python train_reg_crit.py -s dukemtmcreid -t dukemtmcreid --eval-freq 5 --flip-eval --label-smooth --criterion singular --lambda-htri 0.1  --dropout none --data-augment crop --regularizer none --margin 1.2 --train-batch-size 32 --switch-loss -35 --penalty-position after --height 384 --width 128 --fixbase-epoch 10 --optim adam --lr 0.0003 --stepsize 20 40 --max-epoch 60 --save-dir abl_duke_log/baseline_of --arch resnet50_abl_fc1024_fd_none_nohead_dan_none_nohead --gpu-devices 3&

beta=1e-3 part_num=1 nohup python train_reg_crit.py -s dukemtmcreid -t dukemtmcreid --eval-freq 5 --flip-eval --label-smooth --criterion xent --lambda-htri 0.1  --dropout none --data-augment none --regularizer svmo --margin 1.2 --train-batch-size 32 --switch-loss -178 --penalty-position after --height 384 --width 128 --fixbase-epoch 10 --optim adam --lr 0.0003 --stepsize 20 40 --max-epoch 60 --save-dir abl_duke_log/baseline_ow --arch resnet50_abl_fc1024_fd_none_nohead_dan_none_nohead --gpu-devices 4&
