limited=0.1 flip_eval=1 sing_beta=1e-6 beta=1e-3 head_col=2  python train_reg_crit.py -s market1501 -t market1501 --eval-freq 1 --label-smooth --criterion singular_htri --lambda-htri 0.1  --dropout incr --data-augment crop,random-erase --regularizer svmo --margin 1.2 --train-batch-size 64 --switch-loss -178 --penalty-position before,after,cam,pam,layer5 --height 384 --width 128 --fixbase-epoch 10 --optim adam --lr 0.0003 --stepsize 20 40 --max-epoch 200 --save-dir lim_log/market_lim_0.1 --arch resnet50_sf_abd_fc1024_fd_abc_nohead_dan_cam_pam_nohead --gpu-devices 3,2

limited=0.2 flip_eval=1 sing_beta=1e-6 beta=1e-3 head_col=2  python train_reg_crit.py -s market1501 -t market1501 --eval-freq 1 --label-smooth --criterion singular_htri --lambda-htri 0.1  --dropout incr --data-augment crop,random-erase --regularizer svmo --margin 1.2 --train-batch-size 64 --switch-loss -178 --penalty-position before,after,cam,pam,layer5 --height 384 --width 128 --fixbase-epoch 10 --optim adam --lr 0.0003 --stepsize 20 40 --max-epoch 200 --save-dir lim_log/market_lim_0.2 --arch resnet50_sf_abd_fc1024_fd_abc_nohead_dan_cam_pam_nohead --gpu-devices 3,2

limited=0.3 flip_eval=1 sing_beta=1e-6 beta=1e-3 head_col=2  python train_reg_crit.py -s market1501 -t market1501 --eval-freq 1 --label-smooth --criterion singular_htri --lambda-htri 0.1  --dropout incr --data-augment crop,random-erase --regularizer svmo --margin 1.2 --train-batch-size 64 --switch-loss -178 --penalty-position before,after,cam,pam,layer5 --height 384 --width 128 --fixbase-epoch 10 --optim adam --lr 0.0003 --stepsize 20 40 --max-epoch 200 --save-dir lim_log/market_lim_0.3 --arch resnet50_sf_abd_fc1024_fd_abc_nohead_dan_cam_pam_nohead --gpu-devices 3,2

limited=0.4 flip_eval=1 sing_beta=1e-6 beta=1e-3 head_col=2  python train_reg_crit.py -s market1501 -t market1501 --eval-freq 1 --label-smooth --criterion singular_htri --lambda-htri 0.1  --dropout incr --data-augment crop,random-erase --regularizer svmo --margin 1.2 --train-batch-size 64 --switch-loss -178 --penalty-position before,after,cam,pam,layer5 --height 384 --width 128 --fixbase-epoch 10 --optim adam --lr 0.0003 --stepsize 20 40 --max-epoch 200 --save-dir lim_log/market_lim_0.4 --arch resnet50_sf_abd_fc1024_fd_abc_nohead_dan_cam_pam_nohead --gpu-devices 3,2

limited=0.5 flip_eval=1 sing_beta=1e-6 beta=1e-3 head_col=2  python train_reg_crit.py -s market1501 -t market1501 --eval-freq 1 --label-smooth --criterion singular_htri --lambda-htri 0.1  --dropout incr --data-augment crop,random-erase --regularizer svmo --margin 1.2 --train-batch-size 64 --switch-loss -178 --penalty-position before,after,cam,pam,layer5 --height 384 --width 128 --fixbase-epoch 10 --optim adam --lr 0.0003 --stepsize 20 40 --max-epoch 200 --save-dir lim_log/market_lim_0.5 --arch resnet50_sf_abd_fc1024_fd_abc_nohead_dan_cam_pam_nohead --gpu-devices 3,2
